name: DataAccessLayer Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore "#02 CodeFirst/DataAccessLayer/DataAccessLayer.sln"

    - name: Build
      run: dotnet build "#02 CodeFirst/DataAccessLayer/DataAccessLayer.sln" --configuration Release --no-restore
